[package]
name = "cronicle-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
dotenvy = "0.15.7"
reqwest = "0.13.1"
serde = "1.0.228"
serde_json = "1.0.148"
sqlx = "0.8.6"
tokio = "1.49.0"
tokio-cron-scheduler = "0.15.1"
